#!/usr/bin/env python3
"""Replay one collected PegInsertionSide-v1 LeRobot episode with GT actions.

This is a lightweight reconstruction check for the dataset generated by
``collect_maniskill_peg_lerobot.py``. It does not load OpenPI or an SFT
checkpoint. It only:

1. reads one LeRobot episode,
2. resets ManiSkill with the same seed used during collection,
3. sends dataset actions to the ``pd_ee_delta_pose`` environment, and
4. compares replayed states against the dataset states.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np


def _bootstrap_repo_paths() -> Path:
    script_path = Path(__file__).resolve()
    rlinf_root = script_path.parents[2]
    repo_root = rlinf_root.parent
    for candidate in (rlinf_root, repo_root / "openpi-RLT" / "src"):
        candidate_str = str(candidate)
        if candidate.exists() and candidate_str not in sys.path:
            sys.path.insert(0, candidate_str)
    os.environ.setdefault("EMBODIED_PATH", str(script_path.parent))
    return rlinf_root


RLINF_ROOT = _bootstrap_repo_paths()

ENV_ID = "PegInsertionSide-v1"


def _missing_dep_error(package: str) -> RuntimeError:
    return RuntimeError(
        f"Missing runtime dependency '{package}'. Run this in the same server "
        "environment where you collected the ManiSkill dataset."
    )


def _to_numpy(value: Any) -> np.ndarray:
    if hasattr(value, "detach"):
        value = value.detach().cpu().numpy()
    arr = np.asarray(value)
    if arr.ndim > 0 and arr.shape[0] == 1:
        arr = arr[0]
    return arr


def _truthy_first(value: Any) -> bool:
    if value is None:
        return False
    arr = _to_numpy(value).reshape(-1)
    return bool(arr[0]) if arr.size else False


def _quat_wxyz_to_rotvec(quat_wxyz: np.ndarray) -> np.ndarray:
    quat = np.asarray(quat_wxyz, dtype=np.float64)
    norm = np.linalg.norm(quat)
    if norm < 1e-8:
        return np.zeros(3, dtype=np.float32)
    quat = quat / norm
    if quat[0] < 0:
        quat = -quat

    w = np.clip(quat[0], -1.0, 1.0)
    xyz = quat[1:]
    sin_half_angle = np.linalg.norm(xyz)
    if sin_half_angle < 1e-8:
        return (2.0 * xyz).astype(np.float32)
    angle = 2.0 * np.arctan2(sin_half_angle, w)
    return (xyz / sin_half_angle * angle).astype(np.float32)


def _extract_tcp_pose_at_robot_base(env: Any) -> tuple[np.ndarray, np.ndarray]:
    base_env = getattr(env, "unwrapped", env)
    agent = getattr(base_env, "agent", None)
    if agent is None:
        raise RuntimeError("ManiSkill env has no agent")

    pose = getattr(agent, "ee_pose_at_robot_base", None)
    if pose is None:
        robot_pose = getattr(getattr(agent, "robot", None), "pose", None)
        tcp_pose = getattr(getattr(agent, "tcp", None), "pose", None)
        if robot_pose is None or tcp_pose is None:
            raise RuntimeError("Could not get TCP pose in robot base frame")
        pose = robot_pose.inv() * tcp_pose

    raw_pose = getattr(pose, "raw_pose", pose)
    pose_np = _to_numpy(raw_pose).astype(np.float32)
    if pose_np.shape[-1] != 7:
        raise RuntimeError(f"Expected 7D TCP pose, got {pose_np.shape}")
    return pose_np[:3], pose_np[3:]


def _extract_state(env: Any, raw_obs: dict[str, Any]) -> np.ndarray:
    tcp_pos, tcp_quat_wxyz = _extract_tcp_pose_at_robot_base(env)
    qpos = _to_numpy(raw_obs["agent"]["qpos"]).astype(np.float32)
    if qpos.shape[0] < 9:
        raise RuntimeError(f"Expected Panda qpos with at least 9 values, got {qpos.shape}")
    return np.concatenate(
        [tcp_pos.astype(np.float32), _quat_wxyz_to_rotvec(tcp_quat_wxyz), qpos[7:9]],
        axis=0,
    ).astype(np.float32)


def _euler_xyz_to_rotvec(delta_rpy: np.ndarray) -> np.ndarray:
    delta_rpy = np.asarray(delta_rpy, dtype=np.float64).reshape(1, 3)
    roll = delta_rpy[:, 0]
    pitch = delta_rpy[:, 1]
    yaw = delta_rpy[:, 2]

    cr = np.cos(roll * 0.5)
    sr = np.sin(roll * 0.5)
    cp = np.cos(pitch * 0.5)
    sp = np.sin(pitch * 0.5)
    cy = np.cos(yaw * 0.5)
    sy = np.sin(yaw * 0.5)

    qw = cr * cp * cy + sr * sp * sy
    qx = sr * cp * cy - cr * sp * sy
    qy = cr * sp * cy + sr * cp * sy
    qz = cr * cp * sy - sr * sp * cy

    xyz = np.stack([qx, qy, qz], axis=-1)
    norm_xyz = np.linalg.norm(xyz, axis=-1, keepdims=True)
    angle = 2.0 * np.arctan2(norm_xyz, np.abs(qw)[..., None])
    axis = np.divide(
        xyz,
        np.clip(norm_xyz, 1e-8, None),
        out=np.zeros_like(xyz),
        where=norm_xyz > 1e-8,
    )
    return (axis * angle).reshape(3).astype(np.float32)


def _dataset_action_to_env_action(
    action: np.ndarray,
    mode: str,
    *,
    ee_delta_scale: float,
) -> np.ndarray:
    action = np.asarray(action, dtype=np.float32).reshape(-1).copy()
    if action.shape[0] != 7:
        raise RuntimeError(f"Expected 7D dataset action, got {action.shape}")
    if mode == "rlt":
        action[:6] = np.clip(action[:6], -1.0, 1.0)
        action[-1] = np.clip(action[-1], -1.0, 1.0)
    elif mode == "legacy_rlt":
        action[3:6] = _euler_xyz_to_rotvec(action[3:6])
        action[-1] = np.clip(action[-1], -1.0, 1.0)
    elif mode == "rlt_no_gripper_map":
        action[3:6] = _euler_xyz_to_rotvec(action[3:6])
        action[:6] *= float(ee_delta_scale)
        action[:6] = np.clip(action[:6], -1.0, 1.0)
        action[-1] = np.clip(action[-1], -1.0, 1.0)
    elif mode == "raw_scaled":
        action[:6] *= float(ee_delta_scale)
        action[:6] = np.clip(action[:6], -1.0, 1.0)
        action[-1] = 1.0 if action[-1] > 0.5 else -1.0
    elif mode == "raw":
        pass
    else:
        raise ValueError(f"Unknown action mode: {mode}")
    action[-1] = np.clip(action[-1], -1.0, 1.0)
    return action.astype(np.float32)


def _summarize_actions(rows: list[dict[str, Any]], mode: str, ee_delta_scale: float) -> dict[str, Any]:
    raw_actions = np.asarray([_to_numpy(row["actions"]).reshape(-1) for row in rows])
    env_actions = np.asarray(
        [
            _dataset_action_to_env_action(
                row["actions"],
                mode,
                ee_delta_scale=ee_delta_scale,
            )
            for row in rows
        ]
    )
    return {
        "raw_min": raw_actions.min(axis=0).round(6).tolist(),
        "raw_max": raw_actions.max(axis=0).round(6).tolist(),
        "env_min": env_actions.min(axis=0).round(6).tolist(),
        "env_max": env_actions.max(axis=0).round(6).tolist(),
        "raw_first": raw_actions[0].round(6).tolist(),
        "env_first": env_actions[0].round(6).tolist(),
    }


def _episode_seed_from_videos(dataset_path: Path, episode_index: int) -> int | None:
    video_dir = dataset_path.with_name(f"{dataset_path.name}_videos")
    if not video_dir.exists():
        return None
    pattern = f"episode_{episode_index:06d}_seed_*.mp4"
    matches = sorted(video_dir.glob(pattern))
    if not matches:
        return None
    match = re.search(r"_seed_(\d+)\.mp4$", matches[0].name)
    return int(match.group(1)) if match else None


def _episode_bounds(dataset: Any, episode_index: int) -> tuple[int, int]:
    if hasattr(dataset, "episode_data_index") and dataset.episode_data_index is not None:
        data_index = dataset.episode_data_index
        if episode_index < len(data_index["from"]):
            return (
                int(data_index["from"][episode_index].item()),
                int(data_index["to"][episode_index].item()),
            )

    indices = []
    for idx in range(len(dataset)):
        sample = dataset[idx]
        if int(_to_numpy(sample["episode_index"]).reshape(-1)[0]) == episode_index:
            indices.append(idx)
    if not indices:
        raise RuntimeError(f"Episode {episode_index} not found in dataset")
    return min(indices), max(indices) + 1


def _load_episode(dataset_path: Path, episode_index: int) -> list[dict[str, Any]]:
    try:
        from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
    except ImportError as exc:
        raise _missing_dep_error("lerobot") from exc

    dataset = LeRobotDataset(str(dataset_path), download_videos=False)
    start, end = _episode_bounds(dataset, episode_index)
    rows = [dataset[idx] for idx in range(start, end)]
    if not rows:
        raise RuntimeError(f"Episode {episode_index} is empty")
    return rows


def _build_env(args: argparse.Namespace):
    try:
        import gymnasium as gym
    except ImportError as exc:
        raise _missing_dep_error("gymnasium") from exc
    try:
        import mani_skill.envs  # noqa: F401
    except ImportError as exc:
        raise _missing_dep_error("mani_skill") from exc

    sim_freq = max(args.sim_freq, args.control_freq * 8)
    sim_freq -= sim_freq % args.control_freq
    return gym.make(
        ENV_ID,
        obs_mode="rgb",
        control_mode="pd_ee_delta_pose",
        reward_mode=args.reward_mode,
        render_mode="rgb_array",
        sim_backend=args.sim_backend,
        sim_config={"sim_freq": sim_freq, "control_freq": args.control_freq},
        sensor_configs={
            "shader_pack": args.shader_pack,
            "width": args.image_width,
            "height": args.image_height,
        },
        max_episode_steps=args.max_episode_steps,
    )


def _state_error(label: str, replay_state: np.ndarray, dataset_state: np.ndarray) -> str:
    diff = replay_state - np.asarray(dataset_state, dtype=np.float32).reshape(-1)
    return (
        f"{label}: max_abs={float(np.max(np.abs(diff))):.6g} "
        f"mean_abs={float(np.mean(np.abs(diff))):.6g}"
    )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay one collected PegInsertionSide-v1 LeRobot episode."
    )
    parser.add_argument("--dataset-path", required=True)
    parser.add_argument("--episode-index", type=int, default=0)
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="ManiSkill reset seed. Defaults to seed parsed from <dataset>_videos.",
    )
    parser.add_argument("--max-steps", type=int, default=500)
    parser.add_argument("--log-every", type=int, default=25)
    parser.add_argument("--image-width", type=int, default=256)
    parser.add_argument("--image-height", type=int, default=256)
    parser.add_argument("--control-freq", type=int, default=10)
    parser.add_argument("--sim-freq", type=int, default=100)
    parser.add_argument("--sim-backend", default="physx_cpu")
    parser.add_argument("--shader-pack", default="default")
    parser.add_argument("--reward-mode", default="sparse")
    parser.add_argument("--max-episode-steps", type=int, default=500)
    parser.add_argument(
        "--action-mode",
        choices=("rlt", "legacy_rlt", "rlt_no_gripper_map", "raw_scaled", "raw"),
        default="rlt",
        help=(
            "'rlt' matches current RLinf rlt_maniskill env-native action conversion. "
            "'legacy_rlt' is the old no-scale/no-gripper-map path. "
            "'raw' sends dataset action directly."
        ),
    )
    parser.add_argument(
        "--ee-delta-scale",
        type=float,
        default=10.0,
        help="Only used by legacy action modes that replay old physical-delta datasets.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    dataset_path = Path(args.dataset_path).expanduser()
    seed = args.seed
    if seed is None:
        seed = _episode_seed_from_videos(dataset_path, args.episode_index)
    if seed is None:
        raise RuntimeError(
            "Could not infer collection seed. Pass --seed explicitly, or keep "
            f"{dataset_path.with_name(dataset_path.name + '_videos')} with seed in filenames."
        )

    rows = _load_episode(dataset_path, args.episode_index)
    print(
        json.dumps(
            {
                "dataset_path": str(dataset_path),
                "episode_index": args.episode_index,
                "seed": seed,
                "episode_frames": len(rows),
                "action_mode": args.action_mode,
                "ee_delta_scale": args.ee_delta_scale,
            },
            indent=2,
        )
    )
    print(json.dumps({"action_summary": _summarize_actions(rows, args.action_mode, args.ee_delta_scale)}, indent=2))

    env = _build_env(args)
    try:
        raw_obs, _ = env.reset(seed=seed)
        replay_state = _extract_state(env, raw_obs)
        print(_state_error("step0_state_vs_dataset", replay_state, rows[0]["state"]))

        first_success_step = None
        last_info: dict[str, Any] = {}
        steps_run = min(args.max_steps, len(rows))
        stopped_reason = "max_steps"
        for step_idx in range(steps_run):
            action = _dataset_action_to_env_action(
                rows[step_idx]["actions"],
                mode=args.action_mode,
                ee_delta_scale=args.ee_delta_scale,
            )
            raw_obs, reward, terminated, truncated, info = env.step(action)
            last_info = info
            replay_state = _extract_state(env, raw_obs)

            if first_success_step is None and _truthy_first(info.get("success")):
                first_success_step = step_idx + 1

            should_log = (
                step_idx == 0
                or (step_idx + 1) % args.log_every == 0
                or _truthy_first(info.get("success"))
            )
            if should_log:
                target_idx = min(step_idx + 1, len(rows) - 1)
                print(
                    f"step={step_idx + 1} "
                    f"reward={_to_numpy(reward).reshape(-1).tolist()} "
                    f"terminated={_to_numpy(terminated).reshape(-1).tolist()} "
                    f"truncated={_to_numpy(truncated).reshape(-1).tolist()} "
                    f"success={_to_numpy(info.get('success', False)).reshape(-1).tolist()} "
                    + _state_error(
                        f"state_vs_dataset_frame_{target_idx}",
                        replay_state,
                        rows[target_idx]["state"],
                    )
                )

            if _truthy_first(terminated) or _truthy_first(truncated):
                stopped_reason = "terminated_or_truncated"
                break
        else:
            if len(rows) <= args.max_steps:
                stopped_reason = "dataset_end"

        print(f"steps_run={step_idx + 1 if rows else 0}")
        print(f"stopped_reason={stopped_reason}")
        print(f"first_success_step={first_success_step}")
        print(f"final_success={_to_numpy(last_info.get('success', False)).reshape(-1).tolist()}")
    finally:
        env.close()


if __name__ == "__main__":
    main()
